# Generated by Django 5.2.8 on 2026-02-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='desciption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
