# Generated by Django 5.2.8 on 2026-02-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desciption',
            new_name='description',
        ),
    ]
